dataset: ogbg-moltox21
num_workers: 8
model:
  name: GraphMLPMixer
  gnn_type: GINEConv
  nlayer_gnn: 4
  nlayer_mlpmixer: 4
train:
  runs: 4
  lr: 0.01
  lr_patience: 50
  batch_size: 32
  optimizer: ASAM
  epochs: 200
  dropout: 0.3
metis:
  n_patches: 32
