dataset: peptides-func
num_workers: 8
model:
  gMHA_type: MLPMixer
  gnn_type: GINEConv
  nlayer_gnn: 4
  nlayer_mlpmixer: 2
train:
  runs: 4
  lr_patience: 20
  epochs: 200
  mlpmixer_dropout: 0.5
metis:
  n_patches: 32
pos_enc:
  rw_dim: 16