dataset: TreeDataset
depth: 4
num_workers: 8
seed: 0
model:
  gMHA_type: MLPMixer
  gnn_type: GINEConv
  nlayer_gnn: 4
  nlayer_mlpmixer: 4
train:
  lr_patience: 1000
  batch_size: 1024
  epochs: 1000
  runs: 1
metis:
  n_patches: 32
  online: False
  drop_rate: 0.0
pos_enc:
  rw_dim: 0
  lap_dim: 0
  patch_rw_dim: 0