dataset: TreeDataset
depth: 5
num_workers: 8
seed: 0
model:
  name: GraphMLPMixer4TreeNeighbour
  gnn_type: GINEConv
  nlayer_gnn: 4
  nlayer_mlpmixer: 4
  use_patch_pe: False
train:
  lr_patience: 1000
  batch_size: 1024
  epochs: 1000
  runs: 1
metis:
  n_patches: 32
  online: False
  drop_rate: 0.0