dataset: ZINC
num_workers: 8
model:
  name: GraphMLPMixer
  gnn_type: GINEConv
  nlayer_gnn: 4
  nlayer_mlpmixer: 4
train:
  lr_patience: 100
  epochs: 2000
metis:
  n_patches: 32
pos_enc:
  rw_dim: 20